const menuDatas = [
  {
    id: 1,
    title: "Pizza Mixed",
    category: "lunch",
    price: 16.99,
    img: "/images/1-1-450x450.png",
    rate: 4.9,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit Reiciendis perspiciatis iure temporibus minus nostrum tenetur vero",
  },
  {
    id: 2,
    title: "Hamberger Meat",
    category: "lunch",
    price: 12.49,
    img: "/images/2-1-450x450.png",
    rate: 3.7,
    desc: "Lorem ipsum dolor sit amet consecteturtemporibus minus nostrum tenetur vero",
  },
  {
    id: 3,
    title: "Stack Rare",
    category: "dinner",
    price: 20,
    img: "/images/3-1-450x450.png",
    rate: 4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit Reiciendis amet consectetur adipisicing perspiciatis iure temporibus minus nostrum tenetur vero",
  },
  {
    id: 4,
    title: "Strabbery Shake",
    category: "breakfast",
    price: 9,
    img: "/images/5-1-450x450.png",
    rate: 3.9,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit Reiciendis amet consectetur adipisicing perspiciatis iure temporibus minus",
  },
  {
    id: 5,
    title: "Chocolate Ice Creame",
    category: "dinner",
    price: 8.5,
    img: "/images/11-1-450x450.png",
    rate: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit Reiciendis amet consectetur adipisicing perspiciatis iure temporibus minus nostrum tenetur ver",
  },
  {
    id: 6,
    title: "Cheese Berger",
    category: "breakfast",
    price: 14,
    img: "/images/14-1-450x450.png",
    rate: 4.3,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit Reiciendis amet consectetur adipisicing perspiciatis iure temporibus minus nostrum tenetur vero temporibus minus",
  },
  {
    id: 7,
    title: "Shake Pro",
    category: "lunch",
    price: 7,
    img: "/images/23-1-450x450.png",
    rate: 4.1,
    desc: "Lorem Reiciendis amet consectetur adipisicing perspiciatis iure temporibus minus nostrum tenetur vero temporibus minus nostrum tenetur vero",
  },
  {
    id: 8,
    title: "Ice Juice",
    category: "lunch",
    price: 4.99,
    img: "/images/24-1-450x450.png",
    rate: 5,
    desc: "Lorem Reiciendis amet consectetur adipisicing perspiciatistenetur vero temporibus minus nostrum tenetur vero",
  },
];

export default menuDatas;
